// Generated by Wrangler by running `wrangler types`

interface Env {
	IDENTIFIER: string;
	PASSWORD: string;
	LABELER_DID: string;
	SECRET_TMP_TOKEN: string;
	SUBSCRIBE_LABELS_OBJECT: DurableObjectNamespace<import("./src/index").SubscribeLabelsObject>;
	DB: D1Database;
}
