// Generated by Wrangler by running `wrangler types`

interface Env {
	LABEL_SIGNING_KEY: string;
	IDENTIFIER: string;
	PASSWORD: string;
	LABELER_DID: string;
	SECRET_TMP_TOKEN: string;
	SUBSCRIBE_LABELS_OBJECT: DurableObjectNamespace /* SubscribeLabelsObject */;
	DB: D1Database;
}
