// Generated by Wrangler by running `wrangler types`

interface Env {
	IDENTIFIER: "locate.aviva.gay";
	LABELER_DID: "plc:jp6khwtiduqw7y5hm75vh6ve";
	PASSWORD: string;
	LABEL_SIGNING_KEY: string;
	SECRET_TMP_TOKEN: string;
	SUBSCRIBE_LABELS_OBJECT: DurableObjectNamespace<import("./src/index").SubscribeLabelsObject>;
	DB: D1Database;
}
